<?php
require_once __DIR__ . '/includes/db.php';

echo "<h1>Mise à jour des images de la base de données...</h1>";

try {
    $updates = [
    ['id' => '10814', 'image' => '/public/imagesProduits/produits/Couffins 2/B 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Couffins 2/B 2.jpg"]'],
    ['id' => '10821', 'image' => '/public/imagesProduits/produits/Couffins 2/B 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Couffins 2/B 2.jpg"]'],
    ['id' => '10824', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/KK 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/KK 2.jpg"]'],
    ['id' => '10828', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/LL 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/LL 2.jpg"]'],
    ['id' => '10831', 'image' => '/public/imagesProduits/produits/Abat-jours 2/F 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Abat-jours 2/F 2.jpg"]'],
    ['id' => '10833', 'image' => '/public/imagesProduits/produits/Abat-jours 2/E 2.jpg', 'extra_images' => '["/public/imagesProduits/produits/Abat-jours 2/E 2.jpg"]'],
    ['id' => '10835', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/DD 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/DD 2.jpg"]'],
    ['id' => '10837', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/KK 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/KK 2.jpg"]'],
    ['id' => '10841', 'image' => '/public/imagesProduits/produits/Couffins 2/B 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Couffins 2/B 2.jpg"]'],
    ['id' => '10843', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/BB 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/BB 2.jpg"]'],
    ['id' => '10845', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/VV 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/VV 2.jpg"]'],
    ['id' => '10847', 'image' => '/public/imagesProduits/produits/Couffins 2/B 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Couffins 2/B 2.jpg"]'],
    ['id' => '10848', 'image' => '/public/imagesProduits/produits/Couffins 2/B 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Couffins 2/B 2.jpg"]'],
    ['id' => '10850', 'image' => '/public/imagesProduits/produits/Couffins 2/B 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Couffins 2/B 2.jpg"]'],
    ['id' => '10855', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/JJ 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/JJ 2.jpg"]'],
    ['id' => '10857', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/DD 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/DD 2.jpg"]'],
    ['id' => '10859', 'image' => '/public/imagesProduits/produits/Couffins 2/B 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Couffins 2/B 2.jpg"]'],
    ['id' => '10863', 'image' => '/public/imagesProduits/produits/Couffins 2/B 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Couffins 2/B 2.jpg"]'],
    ['id' => '10865', 'image' => '/public/imagesProduits/produits/Couffins 2/B 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Couffins 2/B 2.jpg"]'],
    ['id' => '10868', 'image' => '/public/imagesProduits/produits/Couffins 2/B 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Couffins 2/B 2.jpg"]'],
    ['id' => '10870', 'image' => '/public/imagesProduits/produits/Couffins 2/B 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Couffins 2/B 2.jpg"]'],
    ['id' => '10872', 'image' => '/public/imagesProduits/produits/Couffins 2/B 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Couffins 2/B 2.jpg"]'],
    ['id' => '10874', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/PP 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/PP 2.jpg"]'],
    ['id' => '10880', 'image' => '/public/imagesProduits/produits/Abat-jours 2/F 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Abat-jours 2/F 2.jpg"]'],
    ['id' => '10882', 'image' => '/public/imagesProduits/produits/Abat-jours 2/C 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Abat-jours 2/C 2.jpg"]'],
    ['id' => '10884', 'image' => '/public/imagesProduits/produits/Abat-jours 2/G 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Abat-jours 2/G 2.jpg"]'],
    ['id' => '10886', 'image' => '/public/imagesProduits/produits/Abat-jours 2/C 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Abat-jours 2/C 2.jpg"]'],
    ['id' => '10888', 'image' => '/public/imagesProduits/produits/Abat-jours 2/E 2.jpg', 'extra_images' => '["/public/imagesProduits/produits/Abat-jours 2/E 2.jpg"]'],
    ['id' => '10890', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/EE 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/EE 2.jpg"]'],
    ['id' => '10894', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/MM 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/MM 2.jpg"]'],
    ['id' => '10896', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/MM 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/MM 2.jpg"]'],
    ['id' => '10898', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/WW 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/WW 2.jpg"]'],
    ['id' => '10905', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/WW 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/WW 2.jpg"]'],
    ['id' => '10907', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/NN 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/NN 2.jpg"]'],
    ['id' => '10909', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/CC 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/CC 2.jpg"]'],
    ['id' => '10912', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/HH 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/HH 2.jpg"]'],
    ['id' => '10914', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/UU 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/UU 2.jpg"]'],
    ['id' => '10917', 'image' => '/public/imagesProduits/produits/Abat-jours 2/D 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Abat-jours 2/D 2 (1).jpg"]'],
    ['id' => '10921', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/NN 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/NN 2.jpg"]'],
    ['id' => '10923', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/WW 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/WW 2.jpg"]'],
    ['id' => '10925', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/DD 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/DD 2.jpg"]'],
    ['id' => '10927', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/NN 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/NN 2.jpg"]'],
    ['id' => '10934', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/FF 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/FF 2.jpg"]'],
    ['id' => '10938', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/QQ 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/QQ 2.jpg"]'],
    ['id' => '10940', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/TT 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/TT 2.jpg"]'],
    ['id' => '10945', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/SS 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/SS 2.jpg"]'],
    ['id' => '10948', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/II 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/II 2.jpg"]'],
    ['id' => '10950', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/WW 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/WW 2.jpg"]'],
    ['id' => '10952', 'image' => '/public/imagesProduits/produits/Miroirs 2/B 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Miroirs 2/B 2.jpg"]'],
    ['id' => '10954', 'image' => '/public/imagesProduits/produits/Miroirs 2/B 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Miroirs 2/B 2.jpg"]'],
    ['id' => '10956', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/DD 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/DD 2.jpg"]'],
    ['id' => '10958', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/BB 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/BB 2.jpg"]'],
    ['id' => '10960', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/BB 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/BB 2.jpg"]'],
    ['id' => '10962', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/LL 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/LL 2.jpg"]'],
    ['id' => '10964', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/AA 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/AA 2.jpg"]'],
    ['id' => '10966', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/EE 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/EE 2.jpg"]'],
    ['id' => '10968', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/MM 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/MM 2.jpg"]'],
    ['id' => '10970', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/OO 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/OO 2.png"]'],
    ['id' => '10982', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/HH 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/HH 2.jpg"]'],
    ['id' => '10987', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/WW 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/WW 2.jpg"]'],
    ['id' => '10989', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/TT 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/TT 2.jpg"]'],
    ['id' => '10991', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/ZZ 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/ZZ 2.jpg"]'],
    ['id' => '10998', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/JJ 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/JJ 2.jpg"]'],
    ['id' => '11000', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/TT 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/TT 2.jpg"]'],
    ['id' => '11002', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/RR 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/RR 2.jpg"]'],
    ['id' => '11005', 'image' => '/public/imagesProduits/produits/Miroirs 2/B 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Miroirs 2/B 2.jpg"]'],
    ['id' => '11008', 'image' => '/public/imagesProduits/produits/Lanternes 2/B 1 (2).jpg', 'extra_images' => '["/public/imagesProduits/produits/Lanternes 2/B 2 (2).jpg"]'],
    ['id' => '11013', 'image' => '/public/imagesProduits/produits/Lanternes 2/C 1 (1).jpg', 'extra_images' => '["/public/imagesProduits/produits/Lanternes 2/C 2 (1).jpg"]'],
    ['id' => '11015', 'image' => '/public/imagesProduits/produits/Lanternes 2/B 1 (2).jpg', 'extra_images' => '["/public/imagesProduits/produits/Lanternes 2/B 2 (2).jpg"]'],
    ['id' => '11017', 'image' => '/public/imagesProduits/produits/Abat-jours 2/E 2.jpg', 'extra_images' => '["/public/imagesProduits/produits/Abat-jours 2/E 2.jpg"]'],
    ['id' => '11019', 'image' => '/public/imagesProduits/produits/Abat-jours 2/D 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Abat-jours 2/D 2 (1).jpg"]'],
    ['id' => '11021', 'image' => '/public/imagesProduits/produits/Abat-jours 2/F 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Abat-jours 2/F 2.jpg"]'],
    ['id' => '11023', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/II 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/II 2.jpg"]'],
    ['id' => '11025', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/YY 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/YY 2.jpg"]'],
    ['id' => '11029', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/WW 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/WW 2.jpg"]'],
    ['id' => '11031', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/KK 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/KK 2.jpg"]'],
    ['id' => '11033', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/SS 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/SS 2.jpg"]'],
    ['id' => '11035', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/GG 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/GG 2.jpg"]'],
    ['id' => '11037', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/TT 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/TT 2.jpg"]'],
    ['id' => '11039', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/LL 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/LL 2.jpg"]'],
    ['id' => '11041', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/DD 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/DD 2.jpg"]'],
    ['id' => '11043', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/EE 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/EE 2.jpg"]'],
    ['id' => '11047', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/KK 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/KK 2.jpg"]'],
    ['id' => '11052', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/ZZ 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/ZZ 2.jpg"]'],
    ['id' => '11053', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/EE 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/EE 2.jpg"]'],
    ['id' => '11055', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/ZZ 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/ZZ 2.jpg"]'],
    ['id' => '11057', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/PP 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/PP 2.jpg"]'],
    ['id' => '11059', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/SS 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/SS 2.jpg"]'],
    ['id' => '11061', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/JJ 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/JJ 2.jpg"]'],
    ['id' => '11063', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/VV 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/VV 2.jpg"]'],
    ['id' => '11065', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/BB 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/BB 2.jpg"]'],
    ['id' => '11075', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/PP 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/PP 2.jpg"]'],
    ['id' => '11076', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/YY 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/YY 2.jpg"]'],
    ['id' => '11078', 'image' => '/public/imagesProduits/produits/Abat-jours 2/E 2.jpg', 'extra_images' => '["/public/imagesProduits/produits/Abat-jours 2/E 2.jpg"]'],
    ['id' => '11080', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/RR 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/RR 2.jpg"]'],
    ['id' => '11084', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/WW 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/WW 2.jpg"]'],
    ['id' => '11086', 'image' => '/public/imagesProduits/produits/Miroirs 2/B 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Miroirs 2/B 2.jpg"]'],
    ['id' => '11088', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/HH 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/HH 2.jpg"]'],
    ['id' => '11090', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/JJ 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/JJ 2.jpg"]'],
    ['id' => '11092', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/JJ 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/JJ 2.jpg"]'],
    ['id' => '11094', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/BB 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/BB 2.jpg"]'],
    ['id' => '11096', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/KK 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/KK 2.jpg"]'],
    ['id' => '11100', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/ZZ 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/ZZ 2.jpg"]'],
    ['id' => '11102', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/SS 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/SS 2.jpg"]'],
    ['id' => '11104', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/DD 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/DD 2.jpg"]'],
    ['id' => '11106', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/JJ 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/JJ 2.jpg"]'],
    ['id' => '11109', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/YY 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/YY 2.jpg"]'],
    ['id' => '11110', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/RR 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/RR 2.jpg"]'],
    ['id' => '11112', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/PP 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/PP 2.jpg"]'],
    ['id' => '11114', 'image' => '/public/imagesProduits/produits/Suspensions Luminaires  2/II 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Suspensions Luminaires  2/II 2.jpg"]'],
    ['id' => '11116', 'image' => '/public/imagesProduits/produits/Miroirs 2/B 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Miroirs 2/B 2.jpg"]'],
    ['id' => '11119', 'image' => '/public/imagesProduits/produits/Abat-jours 2/E 2.jpg', 'extra_images' => '["/public/imagesProduits/produits/Abat-jours 2/E 2.jpg"]'],
    ['id' => '11121', 'image' => '/public/imagesProduits/produits/Abat-jours 2/D 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Abat-jours 2/D 2 (1).jpg"]'],
    ['id' => '11123', 'image' => '/public/imagesProduits/produits/Abat-jours 2/D 1.jpg', 'extra_images' => '["/public/imagesProduits/produits/Abat-jours 2/D 2 (1).jpg"]'],
];

    $stmt = $db->prepare("UPDATE products SET image = ?, extra_images = ? WHERE id = ?");
    $count = 0;
    foreach ($updates as $u) {
        $stmt->execute([$u['image'], $u['extra_images'], $u['id']]);
        $count++;
    }
    
    echo "<p>✅ Succès ! $count produits ont été mis à jour avec les nouvelles images.</p>";
    echo "<p><strong style='color:red;'>Veuillez supprimer ce fichier (update_images_db.php) du serveur.</strong></p>";
    
} catch (Exception $e) {
    echo "<h1>Erreur</h1><p>" . htmlspecialchars($e->getMessage()) . "</p>";
}
?>
